### ISSUE TITLE
Sanitise bylines

### ISSUE THREAD

**Issue by imranolas** [Financial-Times/next-harrier#132]
*for posterity*

Bylines sometimes only contain a hyphen `"-"`. Rather than fix this in next-article it makes sense to sanitise this data in Harrier for all apps. Probably not worthwhile picking this up until we start dealing with robustness and platinumification(!?).

https://github.com/Financial-Times/next-article/pull/821

**Comment by matthew-andrews** [comment]
https://github.com/Financial-Times/next-harrier/pull/164
