### ISSUE TITLE
Obliterate brands that are also authors

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-harrier#57]
cc @guyvalerio

**Comment by matthew-andrews** [comment]
Actually — @guyvalerio — do you have a list of brands to keep?

**Comment by matthew-andrews** [comment]
Especially this one!
http://next.ft.com/stream/brandId/NTlhNzEyMzMtZjBjZi00Y2U1LTg0ODUtZWVjNmEyYmU1NzQ2-QnJhbmRz

**Comment by guyvalerio** [comment]
@matthew-andrews This removes brands that are also captured as authors. So will any branding of them in streams be lost? If so, we may need to consider exposing authors...especially for opinion pieces in streams.

In which case, any brand that is not an author should remain a brand. Worth me talking to @musthemag

**Comment by matthew-andrews** [comment]
Nope — the fact they are opinion pieces will mean they retain their branding.

**Comment by matthew-andrews** [comment]
I've applied this logic to Paxman:-
http://next.ft.com/stream/authorsId/Q0ItSlA4OTc2NQ==-QXV0aG9ycw==
