### ISSUE TITLE
Mrs Moneypenny

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-harrier#66]
Brand or Author?
http://next.ft.com/stream/authorsId/Q0ItMDAwMTE4Mg==-QXV0aG9ycw==
http://next.ft.com/stream/brandId/QnJhbmRzXzEyOA==-QnJhbmRz

Place your bets now, @guyvalerio.

I vote brand.

**Comment by guyvalerio** [comment]
It is a brand

On 24 June 2015 at 17:25, Matt Andrews <notifications@github.com> wrote:

> Brand or Author?
> http://next.ft.com/stream/authorsId/Q0ItMDAwMTE4Mg==-QXV0aG9ycw==
> http://next.ft.com/stream/brandId/QnJhbmRzXzEyOA==-QnJhbmRz
>
> Place your bets now, @guyvalerio <https://github.com/guyvalerio>.
>
> I vote brand.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next-harrier/issues/66>.
>



-- 
*Guy Valerio*
Information Architect
FT Technology

+44 (0)20 7873 4761
Number One Southwark Bridge, London, SE1 9HL

<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.
