### ISSUE TITLE
New [Next-only] taxonomy for ratings

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-harrier#68]
```
"metadata": {
  …,
  "rating": [
    {
      term: {
        name: "4 star",
        id: "???",
        attributes: [],
      }
    }
  ]
  …
}
```

Some random [freshly minted uuids](https://www.uuidgenerator.net/):-

```
cefa4ace-9861-41c4-a925-18ba760cb5b0 1 star
1da184ff-c5c9-4ed3-b2f4-b16c296dff2f 2 stars
0cab8d50-0ff3-4af0-8590-068171682901 3 stars
aa973fb5-2695-476a-9661-1b4aac5bb672 4 stars
dd019cd3-39eb-4cd6-8530-14bc9a8baac8 5 stars
```

Temporary Pseudo-TME-style IDs:-

```
Y2VmYTRhY2UtOTg2MS00MWM0LWE5MjUtMThiYTc2MGNiNWIw-bWF0dHJhdGluZw== 1 star
MWRhMTg0ZmYtYzVjOS00ZWQzLWIyZjQtYjE2YzI5NmRmZjJm-bWF0dHJhdGluZw== 2 stars
MGNhYjhkNTAtMGZmMy00YWYwLTg1OTAtMDY4MTcxNjgyOTAx-bWF0dHJhdGluZw== 3 stars
MWRhMTg0ZmYtYzVjOS00ZWQzLWIyZjQtYjE2YzI5NmRmZjJm-bWF0dHJhdGluZw== 4 stars
ZGQwMTljZDMtMzllYi00Y2Q2LTg1MzAtMTRiYzlhOGJhYWM4-bWF0dHJhdGluZw== 5 stars
```

This seem OK to you Mr. V, @guyvalerio ?

**Comment by matthew-andrews** [comment]
@guyvalerio after chatting with @adgad going to throw away the idea of trying to implement something like CAPI v1 and do it like this:-

```
rating: {
  min: 0
  score: 4,
  max: 5
}
```

What think you?

**Comment by guyvalerio** [comment]
Yes. Actually that is what I was discussing with Arjun earlier today when I
came looking for you then realised you wfh. So yes, I think this is close
to what we would model and would allow us to incorporate any type of rating
system.



On 25 June 2015 at 14:39, Matt Andrews <notifications@github.com> wrote:

> @guyvalerio <https://github.com/guyvalerio> after chatting with @adgad
> <https://github.com/adgad> going to throw away the idea of trying to
> implement something like CAPI v1 and do it like this:-
>
> rating: {
>   min: 0
>   score: 4,
>   max: 5
> }
>
> What think you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next-harrier/issues/68#issuecomment-115261033>
> .
>



-- 
*Guy Valerio*
Information Architect
FT Technology

+44 (0)20 7873 4761
Number One Southwark Bridge, London, SE1 9HL

<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by matthew-andrews** [comment]
this is done & rolled out to ~5k documents.

will send you al ink
