### ISSUE TITLE
Regions vs. Sections

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-harrier#69]
e.g. North Korea

http://next.ft.com/stream/sectionsId/ZmM3MzllMTQtMGExOS00Njc4LWI3ZDMtYjg3NDg2Y2U2ZDU5-U2VjdGlvbnM=
http://next.ft.com/stream/regionsId/TnN0ZWluX0dMX0tQ-R0w=

Suspect region should win out……  @guyvalerio ?

**Comment by guyvalerio** [comment]
I should expect the section one to be more accurately applied and be more
likely to be 'about' Korea i.e. better precision.
The region will likely have better recall (i.e more tagging) but at the
expense of precision.



On 24 June 2015 at 18:42, Matt Andrews <notifications@github.com> wrote:

> e.g. North Korea
>
>
> http://next.ft.com/stream/sectionsId/ZmM3MzllMTQtMGExOS00Njc4LWI3ZDMtYjg3NDg2Y2U2ZDU5-U2VjdGlvbnM=
> http://next.ft.com/stream/regionsId/TnN0ZWluX0dMX0tQ-R0w=
>
> Suspect region should win out…… @guyvalerio
> <https://github.com/guyvalerio> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next-harrier/issues/69>.
>



-- 
*Guy Valerio*
Information Architect
FT Technology

+44 (0)20 7873 4761
Number One Southwark Bridge, London, SE1 9HL

<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by matthew-andrews** [comment]
I sort of feel there should be one “thing” for everything……  Ie. no duplicate concepts between sections and regions……  We could still use this data though……

E.g. I was thinking about the columnist-as-a-brand case……  We could keep most of the site's logic much as it is right now but invent a “primaryAuthor” (nonsense, I know…… remember we're hacking on top of V1) then if my code sees one of the banned author brands (e.g. John Authers) it removes that as a brand and adds the author by the same name as a `primaryAuthor`.

Then on the front end of the site we would show the author name by the articles when those articles appear in streams but we wouldn't be splitting our following traffic between the brand and the author pages.

Alternatively we could use the same logic but instead of creating the nonsensical `primaryAuthor` we could add the fact that the author is somehow special to the `attributes` part of the tag.

**Comment by matthew-andrews** [comment]
Or could just force the author to be the `primaryTheme` — then 0 changes needed to the front end

**Comment by matthew-andrews** [comment]
Might try that with Paxman^^

**Comment by matthew-andrews** [comment]
Spot the difference :-)

![screen shot 2015-06-25 at 10 22 29](https://cloud.githubusercontent.com/assets/825088/8351289/22d3e24c-1b24-11e5-8c27-244f4d3020da.png)

![screen shot 2015-06-25 at 10 22 27](https://cloud.githubusercontent.com/assets/825088/8351290/22d77fe2-1b24-11e5-9820-52794f4bf36d.png)
